# handlers/main.yml
- name: Iniciar OpenVPN
  ansible.builtin.service:
    name: openvpn-client@cliente1
    state: started
    enabled: yes

- name: Recargar configuración de red
  ansible.builtin.service:
    name: networking
    state: reloaded
